### ISSUE TITLE
language-javascript?

### ISSUE THREAD

**Issue by brettz9** [Xapphire13/tree-sitter-syntax-visualizer#7]
Hi,

I'm seeing "JavaScript grammar not supported" using a ".js" file with `language-javascript` enabled (I had `atom-typescript` and `language-javascript-plus` but disabled them and restarted).

Also getting "TypeScript grammar not supported" using a ".ts" file with `language-typescript` enabled.

**Comment by aminya** [comment]
You should enable tree-sitter from the settings of Atom.

**Comment by brettz9** [comment]
Thanks a lot!

For anyone else, even after enabling that checkbox, I was getting "JavaScript grammar not supported", despite `language-javascript` appearing to have a tree sitter grammar, but the recent update appears to have fixed it.
