### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by aminya** [Xapphire13/tree-sitter-syntax-visualizer#9]
@Xapphire13 Could you release a new version?

```
apm publish minor
```

**Comment by Xapphire13** [comment]
@aminya, I no longer use Atom, would you be interested in publishing the new version? I can make you a collaborator on the repo which should give you permission to publish https://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#adding-a-collaborator

**Comment by aminya** [comment]
@Xapphire13 Yes, I can do that!
